### ISSUE TITLE
Trek detail page display / App crash

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#123]
I had the impression that CDRP05 was often crashing when scrolling a trek detail page. I thought it was because itinerancy where very long but it also happens on Rando Ecrins on my Android and on Rando Ecrins on IPAD.

**Comment by SBats** [comment]
Nothing special than you can identify to help us reproduce the bug ?

**Comment by camillemonchicourt** [comment]
OK i reproduced it a few times and also on PNM app.
It happens when I launch the app, go on a trek detail page and scroll fast down

**Comment by camillemonchicourt** [comment]
Just tried again, scrolling fast a detail page and the app crashed. (RE on Android 4)

**Comment by SBats** [comment]
I don't have this issue on any of our platforms. Maybe the fact that long parts (pois, touristics, etc..) are now in collapsable element will prevent this (smaller scroll). Coul you try with the version with collapsable containers ?

**Comment by camillemonchicourt** [comment]
Indeed it was hardest to reproduce on 2.1 but it finally happened when I scrolled fast a few times. 
Dont waste too much time if you cant reproduce it. 
It seems like containers helped.
