### ISSUE TITLE
Display problem with responsive images

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#184]
Responsive images dont display well in Geotrek-mobile (Android at least). 
They display well in WEB - http://www.grand-tour-ecrins.fr/informations/les-balcons-des-ecrins/

While in the test versions they were displaying well. 
Maybe it is since we updated these pages with adding some mobile layout in Geotrek-admin Adminsite?

![screenshot_2016-05-17-10-54-01](https://cloud.githubusercontent.com/assets/4418840/15317944/04e1cfcc-1c24-11e6-8e94-07292efc4a7a.jpg)

**Comment by gutard** [comment]
You shouldn't fix height and width of images in flatpage editor if you want them to be responsive. Responsive images takes 100% of the width and scale height to keep ratio. If you fix height, as CSS forces width to 100%, the ratio is not good.

**Comment by camillemonchicourt** [comment]
OK I understand, we checked that. 

But this is the editor that put a height adn width in any case : 

![flatpage-editor](https://cloud.githubusercontent.com/assets/4418840/15923954/07a6a2be-2e30-11e6-9f96-9c039dcb7a5c.jpg)

If I remove the values in the image editor and save, they are still in the source code : 

```
<h6><img class="img-responsive" src="http://www.grand-tour-ecrins.fr/images/custom/pages/gte_061600.jpg" alt="" width="349" height="233" /><em>Randonn&eacute;e p&eacute;destre sur le GR&reg; 54 &copy; Bertrand Bodin - PNE</em></h6>
```

**Comment by gutard** [comment]
OK. It seems adding a CSS rule height: auto fixes the problem.
http://www.silverstripe.org/community/forums/customising-the-cms/show/25447
We just need to figure out how to add this rule.

**Comment by camillemonchicourt** [comment]
OK thanks.

**Comment by SBats** [comment]
This clearly belongs to the admin repository. We won't be adding important! style for overriding inline one.
I suggest we create the according issue in the admin repository.
