### ISSUE TITLE
Add some touristic content fields

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#185]
Actually only image, title and summary are displayed. 

It would be useful to include other information. At least type, phone number, email and postal address.

**Comment by camillemonchicourt** [comment]
After checking again, it is not the summary but only the description field that is actually displayed.

**Comment by SBats** [comment]
Indeed, this display was first created for POI so no contact fields or those kinds of information.
In order to show them, we would need to update the template, which is not on the road for now.

**Comment by camillemonchicourt** [comment]
Fait : https://github.com/GeotrekCE/Geotrek-mobile/commit/12110e487d07ce35c4b389d91827987e45f94194

**Comment by camillemonchicourt** [comment]
Problème revenu dans la V3 qui n'affiche que Titre + Description.
On n'a pas le chapeau, ni le contact, ni info pratiques....

**Comment by bastyen** [comment]
0ffd70d
