### ISSUE TITLE
Put offline tiles below online tiles

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#191]
Offline mobile tiles are set by default to OSM tiles in Geotrek-admin (https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/settings/base.py#L568-L569) and can be overridden with advanced configuration with changing this setting in `geotrek/settings/custom.py`.

Offline maps are displayed above online maps. 
So when you dont use the same tiles but are using Geotrek-mobile online, the tiles are changing depending on the zoom and when you are on a trek that is downloaded online.

![screenshot_20170612-231606_resized](https://user-images.githubusercontent.com/4418840/27055679-71c8442e-4fc5-11e7-93fe-5a257e45e37a.png)

So it may would be better to display online maps above offline maps when you are using the app online.

**Comment by camillemonchicourt** [comment]
I replaced OSM OpenTopoMap (http://wiki.openstreetmap.org/wiki/FR:OpenTopoMap) based on OSM+SRTM for DEM.

I put in `geotrek/settings/custom.py` from Geotrek-admin :
`MOBILE_TILES_URL = 'http://a.tile.opentopomap.org/{z}/{x}/{y}.png'`

It looks a lot better : 

![screenshot_20170707-170955](https://user-images.githubusercontent.com/4418840/27964265-ed27d366-6337-11e7-8a12-bb3fec91843c.png)

![screenshot_20170707-171159](https://user-images.githubusercontent.com/4418840/27964268-eff71c6e-6337-11e7-8484-2a67cbec3f7d.png)

But it would still be useful to display offline maps below online maps. 

Also I noticed that offline maps are not displayed. It displays online maps attribution (IGN Geoportail in our case).

**Comment by camillemonchicourt** [comment]
All these improvements have been done in V3?

**Comment by bastyen** [comment]
I have closed all issues before pushing V3, you can re-open issues if you want.

For now, Online and Offline map use same tiles, only one source (opentopomap in the starter for example).

**Comment by camillemonchicourt** [comment]
Offline maps are still defined in Geotrek-admin settings, so the source can be different from what I see. 
In my tests, Geotrek-mobile online tiles are OpenTopoMap and offline tiles are OpenStreetMaps.

But putting online tiles above offline tiles would still make sense.

**Comment by bastyen** [comment]
For now, there is no plan for an online layer on offline mode.

**Comment by bastyen** [comment]
I close this issue and keep open #215
