### ISSUE TITLE
Add GPX download into

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#192]
Some users of RANDO ECRINS mobile suggested to add the possibility to download GPX into the application, in order to be able to display a trek in other mobile apps. 

Also add KML download ?

**Comment by camillemonchicourt** [comment]
And it could also be interesting to have a link to download the public PDF. 
Only when online to dont download all these files into the app.

**Comment by camillemonchicourt** [comment]
Asked again by some users, to be able to download the GPX files of a trek.

**Comment by bastyen** [comment]
GPX and PDF downloads are now available : a10ec6a
