### ISSUE TITLE
Treks - Messages non traduits

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#200]
Plusieurs messages non traduits : https://github.com/GeotrekCE/Geotrek-mobile/blob/master/src/app/pages/treks/treks.page.html#L29-L31

**Comment by camillemonchicourt** [comment]
Et quelques autres : https://github.com/GeotrekCE/Geotrek-mobile/blob/0ffd70d69ce2965eee693062fd016453c5b71277/src/app/components/poi-details/poi-details.component.html#L24

**Comment by bastyen** [comment]
49506cb

**Comment by camillemonchicourt** [comment]
Merci.
