### ISSUE TITLE
V3 and Italian translations

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#202]
Geotrek-mobile V2 included Italian translations : https://github.com/GeotrekCE/Geotrek-mobile/blob/v2.5.3/app/scripts/globalization/locales.js

No more available in V3 : https://github.com/GeotrekCE/Geotrek-mobile/tree/master/src/assets/i18n

**Comment by bastyen** [comment]
I will try to add Italian translations this week, or next week based on v2 file.

But next for additional languages, I accept pull request too.

**Comment by camillemonchicourt** [comment]
Yes thanks, and for missing or new words, let's wait for Italian to complete it.

**Comment by camillemonchicourt** [comment]
We'll take care of the Italian translation and do a PR as developers have better to do ! :-)

**Comment by bastyen** [comment]
Thanks !

**Comment by bastyen** [comment]
I will take care of en, it, fr files with missing translation #200 but feel free to update files if I make any mistake
