### ISSUE TITLE
V3 - Analytics

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#204]
In V3 settings (https://github.com/GeotrekCE/Geotrek-mobile/blob/master/src/environments/environment.ts), there is no more Google Analytics ID like it was in V2 (https://github.com/GeotrekCE/Geotrek-mobile/blob/v2.5.3/app/scripts/settings.js#L17).

No Analytics is included in V3 ?

**Comment by bastyen** [comment]
Google no longer plans to support Google Analytics for mobile apps by October 2019.
That's why we plan to set up Firebase Analytics (New Google analytics for mobile apps)

https://support.google.com/firebase/answer/9167112?hl=fr

**Comment by camillemonchicourt** [comment]
OK why not if it works similary and is the new way to have detailed statistics.
Thanks

**Comment by bastyen** [comment]
f0ae9d7

**Comment by rorp24** [comment]
How we do if we have no firebase analytic in place?

**Comment by bastyen** [comment]
For instance, you need to remove all Firebase/Google service reference

**Comment by camillemonchicourt** [comment]
If we dont have a Firebase analytics, we dont just have to leave ``useFirebase: false`` setting to have the app working without statistics ?

**Comment by bastyen** [comment]
Look at this

https://github.com/GeotrekCE/Geotrek-mobile#remove-firebase-analytics

Then tell me if this is ok for you too, thanks

**Comment by camillemonchicourt** [comment]
OK with applying this document, we could build the app without setting Firebase analytics.
Thanks.

**Comment by camillemonchicourt** [comment]
Méthode de mise en place : 

- Créer un compte Firebase sur https://firebase.google.com
- Créer un projet pour votre application mobile
- Créer une application Android dans ce projet (permettant de récupérer le fichier ``google-services.json``). Précisions sur https://support.google.com/firebase/answer/7015592?hl=en
- Créer une application iOS dans ce même projet (permettant de récupérer le fichier ``GoogleService-Info.plist``)
- Ajouter les fichiers dans l'arborescence de votre Geotrek-mobile comme indiqué dans la documentation https://github.com/GeotrekCE/Geotrek-mobile#firebase-analytics-configuration
- Créer une propriété dans votre compte Google Analytics associé au projet Firebase analytics (https://support.google.com/analytics/answer/2587086)

**Comment by camillemonchicourt** [comment]
Si on utilise Firebase, il est obligatoire de renseigner l'URL des règles de confidentialité, sinon l'application est rejetée. 

C'est dans "PRésence sur le Play store / Fiche Play store" : 

![image](https://user-images.githubusercontent.com/4418840/60900000-c31a6c80-a26b-11e9-85cb-363a0caa9864.png)
