### ISSUE TITLE
Treks list - Order by distance

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#206]
Dans le V2, si le terminal était localisé, alors les randos étaient ordonnées par distance de leur point de départ part rapport à la position GPS du terminal. 
Sinon par ordre alphabétique, ce qui ne semble pas le cas non plus ?

https://github.com/GeotrekCE/Geotrek-mobile/issues/23

**Comment by bastyen** [comment]
562a310

**Comment by camillemonchicourt** [comment]
Tests sur Android 9, quand je clique sur Trier par Distance, rien ne se passe, la liste reste ordonnée par Ordre alphabétique.

Je suis bien localisé car quand j'affiche la carte des randos, un point bleu marque ma position.

**Comment by camillemonchicourt** [comment]
Même problème avec une 3.1.0 sur un Android 9.
Rien ne se passe quand on clique sur Trier par distance.

APK de test Rando Écrins V3 : https://drive.google.com/file/d/1F3e_0dGcQ83EH6hClg6vS8PVX_-gQtoN/view?usp=sharing

**Comment by camillemonchicourt** [comment]
Dans la V2, quand les randos étaient triées par distance, l'info était affichée pour comprendre le fonctionnement et avoir une idée de cette distance : 

![Screenshot_20190705_204723_com makinacorpus randoecrins](https://user-images.githubusercontent.com/4418840/60741441-adeec680-9f69-11e9-9873-94bdfff6483d.jpg)

Quand on avait la position GPS, les patrimoines et contenus touristiques étaient eux aussi triés par distance avec l'info affichée, très utile quand on parcourt la rando : 

![Screenshot_20190705_204819_com makinacorpus randoecrins](https://user-images.githubusercontent.com/4418840/60741466-c7900e00-9f69-11e9-9da9-ce2bc540fd5f.jpg)

**Comment by camillemonchicourt** [comment]
Idem pour le tri et l'affichage des étapes d'une itinérance : 

![Screenshot_20190705_211050_com ecrins gte](https://user-images.githubusercontent.com/4418840/60741894-813bae80-9f6b-11e9-9616-21849dfcf78f.jpg)

**Comment by bastyen** [comment]
Pour l'ordre le tri c'est ok ?
car ça fonctionne bien lors de mes tests

Si oui il faudrait fermer cette issue et en faire une autre pour l'affichage des distances

**Comment by camillemonchicourt** [comment]
Sur mon terminal, le bouton de tri par distance ne fonctionne pas. 
Il ne se passe toujours rien quand on clique dessus.

**Comment by bastyen** [comment]
Ok je viens de tester, c'est un problème de votre Rando admin / Api.
La liste des treks n'a pas de coordonnées
`Cannot read property 'coordinates' of null`

Donc je ferme cette issue, et en créé une nouvelle pour l'affichage des distances

**Comment by camillemonchicourt** [comment]
OK merci pour l'investigation. 
Je ne vois pas pourquoi car notre Geotrek-admin est à jour et la synchro mobile aussi. 
Mais OK, à voir à ce niveau donc.

**Comment by bastyen** [comment]
Le trek 919357 n'a pas de geometry et stop donc le tri

**Comment by camillemonchicourt** [comment]
OK, bien vu, la géométrie de cette rando était cassée coté Geotrek-admin, suite à l'ajout d'un tronçon. 
Je corrige pour la prochaine synchro.

Ce genre de problème peut se reproduire donc on pourrait imaginer une vérification du champs et si il est vide, mettre la rando à la fin.

**Comment by bastyen** [comment]
C'est bon

865d420

**Comment by camillemonchicourt** [comment]
Merci

**Comment by camillemonchicourt** [comment]
Après re-synchronisation, c'est bon en effet. Merci !
