### ISSUE TITLE
V3 - Filters order

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#209]
Dans la V2, on avait organisé les filtres selon un ordre d'importance : 
![Screenshot_20190509_094051_com makinacorpus randoecrins](https://user-images.githubusercontent.com/4418840/57437652-7eaa2a80-7242-11e9-9ecf-89f8bef51a41.jpg)

L'ordre des filtres de la V3 est bien moins pertinent. 
Le premier filtre doit être la Pratique, ensuite Difficulté, durée, dénivelé, longueur (qui ont disparus dans la V3). 
Thèmes, parcours, vallées et communes sont utiles mais secondaires et avaient été groupés dans Avancés et sous forme de liste déroulante dans la V2.

**Comment by gutard** [comment]
Cf. https://github.com/GeotrekCE/Geotrek-mobile/issues/209

Le choix et l'ordre des filtres sera configurable dans les settings de Geotrek-admin (custom.py). D+ et districts seront également disponibles.

**Comment by camillemonchicourt** [comment]
OK donc l'ordre dans lequel les filtres seront déclarés dans le paramètre ``ENABLED_MOBILE_FILTERS`` définira leur ordre dans l'application mobile : https://github.com/GeotrekCE/Geotrek-admin/pull/1955/files
