### ISSUE TITLE
V3 - Map objects display

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#210]
Dans la V2, on pouvait choisir d'afficher ou non certaines couches sur la carte (Patrimoines, Contenus Touristiques, Etapes). Utiles quand il y a beaucoup d'objets : 

![Screenshot_20190509_102809_com makinacorpus randoecrins](https://user-images.githubusercontent.com/4418840/57439145-b1095700-7245-11e9-88a9-5f53bbf09403.jpg)

**Comment by bastyen** [comment]
7b0e50f
