### ISSUE TITLE
V3 - Map touristic content style

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#211]
Sur la carte, les icônes des objets sont affichés tel quel. 

Dans notre cas, celles des contenus touristiques sont en blanc, donc très peu visibles selon l'emplacement : 
![Screenshot_20190509_101354_io rando ecrins](https://user-images.githubusercontent.com/4418840/57439188-c4b4bd80-7245-11e9-8668-b18af49e4f63.jpg)

Dans la V2, les objets avaient en style et un arrière plan en plus du picto, ce qui garantissait leur visibilité sur la carte :

![Screenshot_20190509_102809_com makinacorpus randoecrins](https://user-images.githubusercontent.com/4418840/57439229-da29e780-7245-11e9-8652-a489012b6c6d.jpg)

**Comment by bastyen** [comment]
6eca9e
