### ISSUE TITLE
POI list - Display icon

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#213]
Afficher l'icone du type de POI comme dans la V2 : 

![Screenshot_20190509_105248_com makinacorpus randoecrins](https://user-images.githubusercontent.com/4418840/57440774-eebbaf00-7248-11e9-8809-c81afe106a29.jpg)

PS : Les légendes des images étaient mieux positionnés aussi dans la V2, moins collé sous l'image

**Comment by bastyen** [comment]
b6b406

**Comment by bastyen** [comment]
6b63ff5
