### ISSUE TITLE
Trek photos credits

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#214]
Display trek photos credits like in V2 : 

![Screenshot_20190509_105637_com makinacorpus randoecrins](https://user-images.githubusercontent.com/4418840/57440974-4823de00-7249-11e9-90ee-631b8000f063.jpg)

Ainsi que les points du slider sous l'image pour bien les voir

**Comment by bastyen** [comment]
52eb67
