### ISSUE TITLE
Offline map zoom level

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#215]
When I am on the map of a trek that has been downloaded, it uses the offline tiles .

But when at a big zoom level, it only has the global offline tiles and it makes map quality problems : 
![Screenshot_20190509_115510_io rando ecrins](https://user-images.githubusercontent.com/4418840/57445004-b371ae00-7251-11e9-9c06-12a7405bc9b2.jpg)

And when moving to another area of the map, it only has global map so the quality is awful : 

![Screenshot_20190509_115533_io rando ecrins](https://user-images.githubusercontent.com/4418840/57445000-b10f5400-7251-11e9-8212-f7247c6bbe3f.jpg)

In V2, when there was no offline tiles somewhere, it displayed online tiles. 

Maybe also put online tiles first when available : https://github.com/GeotrekCE/Geotrek-mobile/issues/191

**Comment by bastyen** [comment]
For now, there is no plan for an online layer on offline mode.

But in your case, the quality of your offline map is not normal. 
You should look your configuration (min zoom / max zoom of offline map.

**Comment by camillemonchicourt** [comment]
Offline maps are defined and generated in Geotrek-admon settings.
Here is what I have : 

```
MOBILE_TILES_URL = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'
```

Outside of the trek, this is the global offline map which is displayed. And this one is just at large level, which is normal.

**Comment by bastyen** [comment]
Oh you should not be able to go outside of the trek bounding box on this map

**Comment by bastyen** [comment]
#218

**Comment by bastyen** [comment]
fab2cd7

**Comment by camillemonchicourt** [comment]
Indeed, I dont have this tiles quality problem anymore.
