### ISSUE TITLE
Map and notification

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#217]
Dès que j'affiche la carte globale, une notification est ajoutée sur mon téléphone, mais je ne vois pas quel en est l'usage ? 

![Screenshot_20190517_143104_io rando ecrins](https://user-images.githubusercontent.com/4418840/57928343-b0f60080-78b0-11e9-8de9-c6c52aa2098d.jpg)

**Comment by bastyen** [comment]
Le GPS est autorisé à fonctionner en background. 
Donc tant qu'il est actif (application ouverte ou en fond), l'utilisateur doit en être notifié. C'est une fonctionnalité d'Android.

**Comment by camillemonchicourt** [comment]
OK OK merci pour les précisions, peut-etre à rendre plus explicite du coup.

**Comment by bastyen** [comment]
La variable 'notificationTitle' des fichiers de traduction est utilisé en tant que titre pour cette notification (Géoréférencement). Elle peut donc être modifié pour chaque client ou sur le projet global :)

**Comment by camillemonchicourt** [comment]
Oui on fera peut-être une contribution d'évolution de certains messages.
