### ISSUE TITLE
V3 - Pb bouton géoloc / "4flèches"

### ISSUE THREAD

**Issue by annmo** [GeotrekCE/Geotrek-mobile#219]
Smartphone Android
sélection d'un treck + sa carte
Clic "bouton des 4 flèche" : ok
Clic "bouton géolocalisation" : zoom trop fort, le treck n'est plus visible

**Comment by lellex** [comment]
Je n'arrive pas à reproduire le bug. Peut être que c'est lié à un trek en particulier.

**Comment by bastyen** [comment]
1783851
