### ISSUE TITLE
V3 - Agrandir zone d'un trek

### ISSUE THREAD

**Issue by annmo** [GeotrekCE/Geotrek-mobile#220]
Sur les trecks un peu longs, le tracé n'est pas toujours entièrement visible sur la carte

**Comment by gutard** [comment]
Dans les tuiles globales on a les zooms 0 à 12 donc on peut dézoomer autant que nécessaire.

**Comment by camillemonchicourt** [comment]
Il s'agit peut-être du zoom initial qui est trop serré et n'affiche qu'une partie de l'itinéraire ?
Pas testé cela en détail.

**Comment by bastyen** [comment]
4624361
