### ISSUE TITLE
Start & End overlay and icon

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#226]
Dans la V2, quand le départ et l'arrivée d'une rando se superposaient, une icône particulière était utilisée pour bien identifier que le départ et l'arrivée étaient au même endroit : 

![Screenshot_20190612_071948_com makinacorpus randoecrins](https://user-images.githubusercontent.com/4418840/59325867-ea216500-8ce4-11e9-890a-2e7b3d6f5695.jpg)

Ce n'est plus le cas dans la V3, du coup on ne voit que le départ ou que l'arrivée, ce qui est moins compréhensible : 

![Screenshot_20190612_073159_io geotrek pymed](https://user-images.githubusercontent.com/4418840/59325888-fdcccb80-8ce4-11e9-84d0-69df0bfbe004.jpg)

**Comment by bastyen** [comment]
C'est toujours le cas, il faut que le trek soit de type boucle tout simplement sinon si ce n'est pas une boucle l'app juge qu'il faut un départ et une arrivée

**Comment by camillemonchicourt** [comment]
OK j'ai testé sur Geotrek PyMed sur des boucles et je ne vois que le drapeau rouge de l'arrivée ?

**Comment by bastyen** [comment]
ah oui pardon ce n'est pas la boucle qui compte mais le point de départ et le point d'arrivée du trek.
Ici c'est une boucle mais le 1er point et dernier point du tableau de coordonnées ne correspondante pas

**Comment by camillemonchicourt** [comment]
OK, je n'ai pas trouvé d'exemple sur Geotrek PyMed parmi leurs 39 boucles où on ne voit que les drapeaux d'arrivée. Mais ils n'ont peut-être pas de cas ?

**Comment by bastyen** [comment]
Je viens de vérifier les données provenant de Geotrek PyMed. 
Et que ce soit pour les boucles ou aller-retour, le premier point est toujours différent du dernier point du tracé mais très proche

**Comment by camillemonchicourt** [comment]
OK

**Comment by camillemonchicourt** [comment]
J'ai cet itinéraire dont le départ et l'arrivée sont exactement les mêmes : http://rando.ecrins-parcnational.fr/a-pied/boucle-du-pigeonnier-dans-le-cirque-du-gioberney/

Dans l'application mobile, seule l'arrivée est affichée : 

![start-trek](https://user-images.githubusercontent.com/4418840/60305792-17ede700-993e-11e9-8e83-2fbf86fbcdde.jpg)

**Comment by bastyen** [comment]
Je viens de vérifier avec vos données pour cette randonnée

Nombre de coordonnées : 1423
Point de départ (index 0 du tableau de coordonnées) : [6.281065, 44.8407952] 
Point d'arrivée (dernier index du tableau de coordonnées, ici 1422) : [6.281064, 44.840798]

Les deux points sont différents donc on affiche le drapeau de départ et le drapeau d'arrivée.
Ici, celui d'arrivée cache celui de départ.

**Comment by camillemonchicourt** [comment]
OK alors c'est peut-être un mauvais exemple.
En effet il y a donc un décalage infime mais réel, que je ne vois pas sur Geotrek-admin.
Merci.
