### ISSUE TITLE
Trek start/end icons styles

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#227]
Dans la V3, les icônes de départ et d'arrivée sont un peu grossières et font plus penser à une course auto qu'à de la randonnée. 

Celles de la V2 étaient plus adaptées et esthétiques.

Aperçu ici : https://github.com/GeotrekCE/Geotrek-mobile/issues/226

**Comment by bastyen** [comment]
Note : Images de la V2 à implémenter disponible ici : https://github.com/GeotrekCE/Geotrek-mobile/tree/v2.X/app/images

Ne pas oublier de transformer les svg en png 48/48
