### ISSUE TITLE
V3. page statique rubique transport 

### ISSUE THREAD

**Issue by lelannl** [GeotrekCE/Geotrek-mobile#229]
bonjour,

Dans la partie "transport" de l'appli les images sont déformées 

![Screenshot_20190613-135029_Rando Ecrins](https://user-images.githubusercontent.com/50708197/59491990-335dea00-8e88-11e9-9fad-694d9586e2ce.jpg)

**Comment by camillemonchicourt** [comment]
Pareil que ce qu'on avait rencontré dans la V2 qui était à corriger au niveau des pages elles-mêmes ?
https://github.com/GeotrekCE/Geotrek-mobile/issues/184

**Comment by bastyen** [comment]
On peut ajouter une règle css pour toutes les images des fiches informations.
Cette règle peut empêcher que la hauteur de l'image soit plus grande que X pixels tout simplement. Donc le rendu ne sera pas parfait, mais toujours plus agréable à l'oeil

**Comment by camillemonchicourt** [comment]
Je sais pas si c'est pertinent.
Dans ce cas je pense que c'est nous qui avons oublié de mettre un style sur cette image mais a vérifier

**Comment by gutard** [comment]
Le problème vient entre autres de tinymce qui ajoute automatiquement les attributs `width=…` et `height=…` en fonction de la taille de la source de l'image. Du coup quand le css rajoute une règle `witdh: 100%` pour le responsive, elle est respectée en largeur, mais la hauteur n'est pas modifiée pour respecter le ratio. Je ne sais pas quel fixes sont faisable et pertinents :
* Modif CSS
* Config ou modif TinyMCE pour supprimer les attributs width/height
* …
