### ISSUE TITLE
Fiche rando - Manque le champ Ambiance

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#236]
Le champs ``ambiance`` est complémentaire du champs ``chapeau`` : http://rando.ecrins-parcnational.fr/a-pied/boucle-du-pigeonnier-dans-le-cirque-du-gioberney/

Dans la V3, seul le chapeau est affiché. Il faut donc ajouter le champs ``ambiance`` sous le chapeau. 
Avec le chapeau en gras comme actuellement, et l'ambiance en texte normal en dessous.

**Comment by bastyen** [comment]
f650ac8

**Comment by gutard** [comment]
Le champ "ambiance" est dispos dans l'API mobile à partir de la version 2.27.9 de Geotrek-admin.
