### ISSUE TITLE
Treks list - List type button to invert

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#238]
En haut à droite de la liste, un bouton permet de passer la liste des randos du mode liste (1 rando par ligne) au mode bloc (2 randos par ligne). Mais les icônes devraient être inversé : 
- Bouton bloc quand on est en mode liste
- Et bouton liste quand on est en mode bloc

**Comment by bastyen** [comment]
ce4238d
