### ISSUE TITLE
Modal touristic content and icon

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#239]
Quand on est sur la carte d'une rando et que l'on clique sur un contenu touristique, celle-ci cherche à afficher un picto, mais il n'en trouve pas. 

![ct-modal](https://user-images.githubusercontent.com/4418840/60306059-2688ce00-993f-11e9-8b9f-5b7f97f40acf.jpg)

Certainement car il utilise le même template que les patrimoines qui affiche de manière pertinente l'icone du type de POI à cet endroit. 

Proposition : 
- Afficher l'icone du la catégorie du contenu touristique (idéal mais pas sur qu'on l'ait ?)
- Ne pas afficher d'icone de type si on est sur la modale d'un contenu touristique. Uniquement si c'est la modale d'un POI

**Comment by bastyen** [comment]
9a3c273
