### ISSUE TITLE
Fiche rando - Affichage départ et arrivée

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#240]
Dans la V3, les champs départ et arrivée affichent la commune en plus de l'info textuelle : 

![depart-display](https://user-images.githubusercontent.com/4418840/60306433-6e5c2500-9940-11e9-9760-fbc18378e867.jpg)

Il faudrait séparer ces 2 infos par un tiret par exemple. 

Mais cela peut aussi induire en erreur. 
Le nom de la commune étant souvent le nom du village de la commune, on peut penser que le départ et/ou l'arrivée sont au niveau du village alors que pas du tout.

Du coup, il faut peut-être plutôt revenir à l'affichage de la V2 et de Geotrek-rando qui dissocie les infos. 
- Communes : XXX, YYYY
- Départ : Texte
- Arrivée : Texte

**Comment by bastyen** [comment]
On a ajouté un saut de ligne entre la commune et l'information supplémentaire (meilleure lisibilité sur mobile)

Par contre, on affiche toujours tel quel la commune et l'information supplémentaire car elle convient au plus grand nombre

f650ac8

**Comment by camillemonchicourt** [comment]
OK pour l'affichage avec l'info Commune dans les blocs Départ et Arrivée.
Par contre, il faut vraiment rajouter le label "Commune :" devant l'info de la commune sinon c'est faux. Le nom de la commune étant la plupart du temps le nom du village de la commune, cela laisse penser que le départ et l'arrivée sont dans le village, alors qu'ils sont dans la commune...

Dans mon exemple, ça donnerait donc : 

**Départ**
Commune : La Chapelle-en-Valgaudemar
Au parking du Gioberney

**Arrivée**
Commune : La Chapelle-en-Valgaudemar
Gioberney

Merci.

**Comment by bastyen** [comment]
Ok je rajoute cette informatio

**Comment by bastyen** [comment]
a94b4aa

**Comment by camillemonchicourt** [comment]
Merci.
