### ISSUE TITLE
Trek page - Active URL

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#241]
Dans le détail des contenus touristiques d'une fiche rando, les URL des sites web des contenus touristiques ne sont pas cliquables. 

Il serait bien que les utilisateurs puissent y accéder avec un ``<a href...>``

**Comment by camillemonchicourt** [comment]
@rorp24, il faudrait faire la même chose dans la modale d'un contenu touristique affiché quand on y accède par la carte d'une rando. 

Une autre amélioration serait de ne pas rendre une URL cliquable si elle ne commence pas par ``http``.

**Comment by bastyen** [comment]
da44368
