### ISSUE TITLE
Long trek title on detail page

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#242]
Comme pour la liste des randos (https://github.com/GeotrekCE/Geotrek-mobile/issues/203), les noms des randos sur les fiche détail sont coupés la plupart du temps. 

C'est moins esthétique, mais il importe d'afficher les noms complets car sinon on ne sait pas toujours sur quelle rando on se trouve. Donc les passer sur 2 lignes si nécessaire. Quitte à ne pas les mettre dans la navbar si besoin, comme c'était dans la V1 ?

![Screenshot_20190703_181939_com makinacorpus randoecrins](https://user-images.githubusercontent.com/4418840/60608216-3a10ba80-9dbf-11e9-8ffb-6e927e4c2a25.jpg)

**Comment by bastyen** [comment]
6fbe862
