### ISSUE TITLE
Filters without content

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#243]
In V3, filters values are generated by ``sync_mobile`` command and saved in the files by languages in API data ``mobile/fr/settings.json``.

Some Geotrek-admin settings can be overriden in advanced configuation (``custom.py``) based on default values : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/settings/base.py#L597-L627

Same for enabled filters and there order : https://github.com/GeotrekCE/Geotrek-admin/blob/master/geotrek/settings/base.py#L671-L682

Par contre, dans la V3, toutes les typologies de filtres sont intégrées, même celles n'ayant aucun contenu. 

Ainsi dans Rando Ecrins, 5 pratiques sont proposées dans les filtres, alors que seulement 2 pratiques ont des contenus : 

![Screenshot_20190705_085722_io rando ecrins](https://user-images.githubusercontent.com/4418840/60710860-e5328880-9f13-11e9-8aba-7fef558e0444.jpg)

C'est certainement à gérer au niveau de Geotrek-admin ? Mais on peut aussi imaginer que les valeurs de filtres soient limitées au niveau de Geotrek-rando ?

**Comment by bastyen** [comment]
> C'est certainement à gérer au niveau de Geotrek-admin ?

Oui

**Comment by bastyen** [comment]
Apparemment, les types non utilisés doivent être supprimés manuellement de l'admin si non utilisés.

**Comment by camillemonchicourt** [comment]
OK mais ça ne peut pas fonctionner comme ça, dans le cas où un Geotrek-admin publie sur plusieurs portails, donc plusieurs Geotrek-mobile qui ont des contenus et donc des valeurs de filtre différentes. 
Ou alors c'est aussi au niveau de la synchro-mobile qu'il doit n'intégrer les filtres et valeurs de filtres uniquement concernant les contenus du portail cible. Mais ça complexifie la synchro mobile je pense.
