### ISSUE TITLE
V3 - Multi-day trekking / Itinerance

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#246]
Dans la V2, les séjours itinérants étaient intégrés de manière similaire à ce qui est fait dans Geotrek-rando. Ce n'est pas le cas actuellement dans la V3 (3.1.0).

Fonctionnement V2 : 

Seules les fiches mères sont affichées dans la liste des randos. 
Les étapes d'une fiche mère sont embarquées mais pas affichées dans la liste des randos (car non publiées). 

Actuellement dans la V3, les étapes non publiées d'un séjour publié sont bien embarquées mais affichées dans la liste des randos.

Sur la fiche détail d'une fiche Séjour, un bloc affiche la liste ordonnée de ses étapes : 

![Screenshot_20190705_204256_com ecrins gte](https://user-images.githubusercontent.com/4418840/60740679-f0fb6a80-9f66-11e9-9b4d-326f371c220f.jpg)

La carte de la fiche Séjour permet d'afficher/masquer les étapes : 

![Screenshot_20190705_204314_com ecrins gte_resized_20190705_084551509](https://user-images.githubusercontent.com/4418840/60740689-f6f14b80-9f66-11e9-8453-d3f5c9a7c786.jpg)

On voit donc les étapes du séjour sur la carte du séjour : 

![Screenshot_20190705_204322_com ecrins gte_resized_20190705_084551627](https://user-images.githubusercontent.com/4418840/60740699-fc4e9600-9f66-11e9-845e-46d640cc9376.jpg)

Depuis la fiche Séjour on peut accéder à la fiche d'une étape (depuis la liste des étape ou la carte du séjour). Depuis cette fiche, on voit le séjour et on peut naviguer entre ses étapes : 

![Screenshot_20190705_204332_com ecrins gte](https://user-images.githubusercontent.com/4418840/60740703-01abe080-9f67-11e9-8db0-e8fc078e469a.jpg)

**Comment by bastyen** [comment]
#83aecd0

**Comment by bastyen** [comment]
- [ ] Ajouter accès aux étapes précédente/suivante
- [ ] Changer le style de la layer des randonnées enfants sur la map de la randonnée parent
- [ ] Ajouter le numéro de l'étape dans la fiche enfant

**Comment by bastyen** [comment]
L'itinérance est maintenant disponible.

Une nouvelle release devrai être disponible cette semaine

Si tu peux tester et donner ton avis, Merci 👍

**Comment by camillemonchicourt** [comment]
OK merci. 
On a déjà mis à jour notre Geotrek-admin.
Reste à faire une synchro mobile avec de l'itinérance et tester un nouveau déploiement de l'application mobile, sujet que je maîtrise peu. 
On teste dès que possible.

**Comment by camillemonchicourt** [comment]
A noter que dans la commande de synchronisation ``sync_mobile``, les étapes s'appuient sur les médias du séjour (itinéraire parent) pour ne pas dupliquer les médias qui sont censés être les mêmes entre le séjour et les étapes. Cependant si les étapes sont légèrement différentes des séjours, les éventuels POI rattachées à une étape mais pas au séjour n'auront pas leurs images synchronisées et donc non affichés sur la fiche étape.
Normalement les séjours et les étapes devraient avoir un tracé similaire, mais ce cas particulier a été observé, donc noté ici pour mémoire.
