### ISSUE TITLE
V3 - Collapse additional content

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#247]
Après les détails sur la rando, la fiche affiche les éventuels listes de Patrimoines et des Contenus touristiques associés à la rando. 

Ces listes étant longues, elles avaient été regroupées dans des blocs repliables dans la V2 pour plus de visibilité : 

![Screenshot_20190705_211050_com ecrins gte](https://user-images.githubusercontent.com/4418840/60741601-60268e00-9f6a-11e9-896c-f62766c145a4.jpg)

Un paramètre permettait de définir le comportement par défaut (un item déplié par défaut ou tous les blocs pliés par défaut) : https://github.com/GeotrekCE/Geotrek-mobile/issues/117

**Comment by bastyen** [comment]
Les pois et contenus touristiques sont déjà dans des accordéons. U
Il faut appuyer sur le bouton afficher tous pour tout voir.

On affiche par défaut 5 élements, c'est un choix.

Par contre, on peut envisager de rajouter dans les paramètres d'environnement le nombre d'éléments afficher par défaut, donc 0 pour un accordéon complètement fermé par défaut.

**Comment by bastyen** [comment]
c7105c0
