### ISSUE TITLE
V3 - Réinitialiser filtres et quitter 

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#248]
- J'applique un filtre
- J'accède à la liste des randos filtrées
- Je retourne aux filtres et les réinitialise avec "Effacer tout"
- Je quitte les filtres avec la croix
- Le filtre précédent est toujours appliqué à la liste des randos

**Comment by bastyen** [comment]
C'est le fonctionnement normal, il faut valider tout changement de filtre avec le bouton "afficher les xxx" du bas.

La flèche permet d'annuler
