### ISSUE TITLE
Maps - Credits and scale missing

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#249]
It should be displayed on maps

**Comment by bastyen** [comment]
**_If your map does not use Mapbox designs, data, hosting, or other Mapbox APIs, Mapbox does not require you to provide attribution in either form._**

Dans notre cas, pas besoin d'ajouter l'attribution. Par contre si un client utilise les services de Mapbox, il faudra l'afficher oui

**Comment by bastyen** [comment]
ad43469

**Comment by camillemonchicourt** [comment]
OK Mapbox ne le demande pas si ce sont pas ses fonds mais les producteurs l'oblige. Car quand on utilise un fond OSM ou OpenTopoMap ou encore pire IGN, on est dans l'obligation de le créditer sur la carte

**Comment by bastyen** [comment]
Ah oui je rajouterai une option d'env qui sera affiché sur la carte alors car la source/fonctionnement peut changer en fonction des apps

**Comment by camillemonchicourt** [comment]
Merci

**Comment by bastyen** [comment]
6fbfc2f
