### ISSUE TITLE
Changer le terme  « Distance » mettre « A proximité »

### ISSUE THREAD

**Issue by annmo** [GeotrekCE/Geotrek-mobile#252]
Suggestion de la Communauté de Communes Coeur et Coteaux Comminges (31) :

- Au lieu de « distance » mettre « A proximité »

**Comment by camillemonchicourt** [comment]
Pour la distance du point de départ par rapport à la position GPS actuelle ?
En effet distance peut porter à confusion avec la longueur de la rando.
Mais alors peut-être plutôt "Trier par proximité". 
Et pour que cela soit compréhensible afficher "à xxx km" au niveau de chaque rando comme dans la v1

**Comment by camillemonchicourt** [comment]
En lien avec https://github.com/GeotrekCE/Geotrek-mobile/issues/251
