### ISSUE TITLE
V3 - Section Hébergement trop longue

### ISSUE THREAD

**Issue by annmo** [GeotrekCE/Geotrek-mobile#254]
Remarque du Sisteronais Buech

La section "hébergements" est trop longue dans les randos. Il faudrait avoir une rubrique déroulante pour réduire et n’avoir que les photos et le nom de l’hébergement.

**Comment by camillemonchicourt** [comment]
Oui c'est parfois long, mais la plupart des utilisateurs ne souhaitent pas réduire les contenus. Au contraire, on a souhaité intégrer tout le détail des contenus touristiques : https://github.com/GeotrekCE/Geotrek-mobile/issues/185. Si on n'a pas le descriptif, le numéro de téléphone pour pouvoir contacter l'hébergement ainsi que les infos pratiques, les contenus touristiques perdent tout leur intérêt. 

Mais si je comprends bien ce qui est proposé, on pourrait imaginer un affichage différent ? En effet replier les hébergements par défaut avec le infos minimales et n'afficher le détail d'un Contenu touristique qu'au clic sur celui-ci pourrait être une piste intéressante. 

Il faut peut-être aussi plutôt imaginer la fiche détail autrement. Avec un onglet dédié aux patrimoines et un autre aux Contenus touristiques pour que les fiches détails soient moins longues ?

**Comment by bastyen** [comment]
Je peux garder seulement l'image et le nom du contenu.

Puis ajouter une icône / Button "En savoir plus" qui affiche le contenu au complet dans une nouvelle fenêtre (comme sur la carte)

Si c'est ok, doit-on le faire seulement sur les hébergements ou tous les types de contenus ? (Patrimoines, contenu touristiques etc)

**Comment by camillemonchicourt** [comment]
Je ne sais pas si c'est mieux d'ouvrir une modale à chaque fois qu'on veut voir le détail d'un hébergement. 
Dans tous les cas, si on le fait pour les hébergements, il ne faut pas le faire spécifiquement sur cette catégorie, mais au moins pour tous les Contenus touristiques qui doivent être traités de manière commune et générique. 

J'aurai plutôt tendance à penser qu'il faut d'abord avoir une réflexion globale sur l'organisation et la hiérarchie des contenus avant de faire cela.

**Comment by annmo** [comment]
Dans l'immédiat, on ne fait pas évoluer cette partie.
Il faudrait effectivement avoir un raisonnement plus large, et certainement apporter ce comportement sur tous les contenus touristiques.

Si une réflexion venait à aboutir, cela pourrait être développer dans le cadre d'une évolution et donc d'un chiffrage préalable.
