### ISSUE TITLE
Filtre - amélioration UI

### ISSUE THREAD

**Issue by samuelpriou** [GeotrekCE/Geotrek-mobile#263]
Bonjour,
Lorsqu'un utilisateur souhaite quitter le menu filtre après avoir avoir activé un filtre puis cliqué sur "Effacer tout", la croix porte à confusion. L'utilisateur croit fermer les filtres avec la suppression du filtre or celui reste actif car il faut au préalable cliquer sur afficher les X randonnées.

La suite des étapes ne semble pas logique ...

![Rando Mercantour](https://user-images.githubusercontent.com/9743288/69873583-088e1380-12b9-11ea-9a54-14b2948584e8.jpg)

**Comment by bastyen** [comment]
Effectivement il faut touché le bouton "Afficher les" pour prendre en compte les modifications.

On a besoin d'un bouton "Annuler" (ici la croix) pour ... annuler toutes modifications en cours.
Le cheminement me parait donc logique.

C'est peut être plus clair en rajoutant un libellé "Annuler" avec la croix ? ou tout simplement remplacer la croix par le libellé "Annuler" ?
