### ISSUE TITLE
Modification fonctionnalité de recherche

### ISSUE THREAD

**Issue by annmo** [GeotrekCE/Geotrek-mobile#265]
**Proposition de la CC Coeur et Coteaux Comminges (31) le 13/03/20**

Le bouton recherche (à côté de filtres) pourrait-il englober toute recherche du nom (nom de la rando & filtres communes).

**Comment by annmo** [comment]
Précisions apportées par Makina Corpus

La barre de recherche a été développée pour rechercher une randonnée à partir de son nom.

L'ensemble des filtres propose des recherches complémentaires, notamment celui de filtrer par communes.

Il nous semble que c'est peu intuitif de mélanger les recherches par une seule entrée dans une application.

A voir ce qu'en pense la communauté

**Comment by camillemonchicourt** [comment]
Oui je pense aussi que c'est mieux de le limiter aux noms des randos. 
Ou alors qu'il cherche sur TOUTES les données, mais cela serait lourd. 
Donc ajouter uniquement les COMMUNES en plus des NOMS, ne me semble pas très compréhensible, ni intuitif pour les utilisateurs.
