### ISSUE TITLE
V3 - Off-line mode - Itinérance - Affichage fond de carte

### ISSUE THREAD

**Issue by JeanLenormand** [GeotrekCE/Geotrek-mobile#266]
Bonjour, 

Je cherche des infos sur le fonctionnement du fond de carte en mode off-line pour les itinérances :

1. Il est possible de télécharger les données d'un itinéraire parent mais pas d'une étape. Quelqu'un saurait il me dire le fonctionnement de cette option ?

2. En mode hors ligne, les tuiles générées lors de la synchro sync-mobile me permettent de bien afficher le fond de carte de l'itinéraire parent avec le niveau de zoom choisi. Par contre, le fond de carte des étapes ne s'affiche pas correctement. Comment cela fonctionne t il ?

**Conf.**
GTA 2.32.10 / GTM 3.3.2
Fichier custom.py
MOBILE_TILES_GLOBAL_ZOOMS = range(11)
MOBILE_TILES_LOW_ZOOMS = range(8, 11)
MOBILE_TILES_HIGH_ZOOMS = range(11,14)

**Capture de l'itinéraire parent au zoom 14**
![90668218_638453916995964_7224189752705024000_n](https://user-images.githubusercontent.com/33653562/77327347-67214680-6d1b-11ea-9aea-35c76ea53466.jpg)

**Capture de l'étape au zoom 14 (même zone que l'iti parent)**
![90926832_2850058821729147_1437713239747067904_n](https://user-images.githubusercontent.com/33653562/77327354-6be5fa80-6d1b-11ea-8500-bd47a8d9ac62.jpg)

Merci

**Comment by bastyen** [comment]
Bonjour,

1 : On ne peut pas télécharger une étape seule. Soit elle doit aussi être publié en tant de randonnée simple soit on télécharge toute l'itinérance.

2 : C'est une configuration Geotrek Admin, je ne vais pas pouvoir y répondre. Par contre être vous sûr d'utiliser la dernière version de Geotrek Mobile ?

**Comment by camillemonchicourt** [comment]
OK merci pour ces éléments. En effet pour l'itinérance, on pourrait imaginer proposer l'inverse comme évolution : ne pouvoir télécharger que certaines étapes. Une itinérance et tout son contenu offline pouvait être très volumineux.

**Comment by JeanLenormand** [comment]
1. Ok
2. Oui j'utilise la version 3.3.2.

Merci Bastyen

**Comment by JonathanALLAIN** [comment]
Salut à tous,
Je partage ici les récents échanges que j'ai eus avec Makina sur le off-line des randos itinérantes, notamment le bug des tuiles qui ne s'affichent pas au niveau de zoom inf 500m sur les étapes des randos itinérantes. J'avais déjà fait part de ce bug à Camille. J'étais en train de publier cela quand j'ai trouvé ce sujet et donc je réponds plutôt.

- Pour avoir les étapes des randos itinérantes en off-line il faut télécharger la rando mère (en fait il n'y a que cette fonction qui est actuellement possible sur la V.3.2.2). Toutes les étapes, ainsi que la rando mère, sont alors accessibles off line. Il y a effectivement un bouton "télécharger" actuellement sur les étapes mais aucune requête opérationnelle derrière. Visiblement le CD44 finance à ce jour le dév pour enlever le bouton "télécharger" sur les étapes car cela n'a en effet que peu de pertinence de les télécharger une par une et indépendamment de leur fiche mère. En téléchargeant la rando mère, on a toutes les étapes en off-line.

- **BUG fond de carte sur les étapes en Off-line** : ce problème majeur a persisté. Nos utilisateurs nous l'ont rapidement fait remonter fin février. J'étais en **V 3.2.2.** Nous avons financé un correctif réalisé par Makina ce mois-ci avec re-depôt sur les deux stores. Le BUG est ok en **V 3.3.2**. Il faut donc la re déposer sur vos stores.

**Comment by camillemonchicourt** [comment]
Il y a eu un correctif récent dans la version 3.3.3 (https://github.com/GeotrekCE/Geotrek-mobile/releases) mais je ne sais pas ce qu'il corrige exactement : https://github.com/GeotrekCE/Geotrek-mobile/compare/3.3.2...3.3.3

**Comment by JonathanALLAIN** [comment]
Ok ! merci !
Je pense que c'est justement le non téléchargement pour le off line des étapes indépendamment de leur fiche mère.

**Comment by bastyen** [comment]
Effectivement la version 3.3.3 résout 3 problèmes : 

- L'affichage du fond de carte sur les étapes hors ligne (pour une randonnée mais surtout ici pour une itinérance)
- Le bouton de téléchargement fonctionne désormais depuis une étape. Celui-ci télécharge toute l'itinérance depuis l'étape, donc pas seulement l'étape
- La version iOS utilise désormais WKWEBVIEW (améliore les performances et sécurité). Depuis ce mois-ci, Apple n'autorise plus le déploiement de nouvelles applications sans WKWEBVIEW. Et n'autorisera plus les mises à jour sans WKWEBVIEW d'ici la fin de l'année.

**Comment by JeanLenormand** [comment]
Version 3.3.3 testé. En effet les problèmes ont été résolus. Merci à Bastyen pour la mise à jour !
