### ISSUE TITLE
Question customisation

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-mobile#267]
Bonjour Bastien,

avant tout merci encore pour ta documentation et ton aide pendant la formation, j'ai commencé à faire des build de l'apk de mon côté. 👍 

J'ai quelques questions concernant la customisation. Sachant que l'application récupère directement les données depuis le dossier de synchro :

 - Est-ce qu'il est possible de choisir les pratiques qui vont êtres publiées sur l'appli mobile ? Par exemple, le Geotrek-rando ne va pas afficher une pratique s'il elle n'a pas de contenu (malgré le fait qu'elle soit créée dans l'admin). Par contre la pratique remonte quand même sur l'application mobile.

- Pour les différents niveaux de difficultés, on en a plusieurs personnalisés par pratique, ce qui fait que chaque niveaux de difficultés remontent en vrac aussi sur l'application. Est-ce qu'il est possible aussi de filtrer les niveaux de difficultés qui remontent sur l'appli ou bien il faut les modifier sur le Geotrek-admin ?

Merci encore à toi et à bientôt.

**Comment by bastyen** [comment]
Bonjour,

Toutes les données des filtres proviennent directement de l'api de Geotrek depuis le fichier https://api-url-client/mobile/settings.json

Donc oui il est possible de les paramétrer donc d'ajouter un filtre, supprimer un filtre ou supprimer une donnée d'un filtre.

Néanmoins, c'est une configuration à faire directement sur l'api de Geotrek (distinct de la version rando), mais je n'ai pas assez de connaissance du back end pour aider plus.
L'application mobile prendra en compte les nouvelles données sans avoir besoin de refaire un build/déploiement.

**Comment by camillemonchicourt** [comment]
En effet ces sujets concernent plutôt Geotrek-admin.
Concernant les filtres sans valeur affichés dans l'application ont été discutés ici : https://github.com/GeotrekCE/Geotrek-mobile/issues/243
Discuté aussi sur Geotrek-admin : https://github.com/GeotrekCE/Geotrek-admin/pull/2058

Pour le second point, le fait d'avoir des typologies de difficulté différentes selon les pratiques n'est pas prévu dans la BDD ni le fonctionnement actuel de Geotrek-admin. Pour faire cela correctement, il faudrait ajouter une table de correspondance entre niveaux de difficultés et pratiques dans la BDD de Geotrek. 
Donc si cela a été fait en l'état c'est du bidouillage non prévu.

**Comment by mviadere-openig** [comment]
@camillemonchicourt en fait ils ont juste créé plusieurs niveaux de difficultés identiques avec une image différentes (différencié par pratique), mais du coup elle remontent toutes sur l'appli mobile.

**Comment by camillemonchicourt** [comment]
> @camillemonchicourt en fait ils ont juste créé plusieurs niveaux de difficultés identiques avec une image différentes (différencié par pratique), mais du coup elle remontent toutes sur l'appli mobile.

Oui c'est assez logique car c'est pas prévu et pas modélisé dans la BDD.

**Comment by mviadere-openig** [comment]
Pour ce qui est du settings.json, je l'ai regardé, on peut effectivement ajouter et supprimer ce que l'on souhaite, le problème c'est que comme c'est synchronisé tous les jours, ça annulerait les modifications faites, je vais fouiller cette piste.

**Comment by mviadere-openig** [comment]
On a finalement décidé de garder les mêmes niveaux de difficultés pour chaque pratique.
