### ISSUE TITLE
Affichage d'un polygone sur la carte

### ISSUE THREAD

**Issue by JeanLenormand** [GeotrekCE/Geotrek-mobile#268]
J'ai un polygone qui s’affiche sur le fond de carte de l'application. Il est visible en permanence que ce soit sur la carte d'accueil ou sur n'importe quel itinéraire. Dans GTA je n'ai aucune donnée visible dans cette zone (itinéraire, POIs ou CT, ...)..

**Conf.**
GTA 2.32.10 / GTM 3.3.3

**Captures (écran d'accueil)**

![93796006_212761300027095_4321969901418840064_n](https://user-images.githubusercontent.com/33653562/79327541-f08bf900-7f14-11ea-9b6f-162899642aba.jpg)

![93646690_255226109203297_7574845820646719488_n](https://user-images.githubusercontent.com/33653562/79327578-ff72ab80-7f14-11ea-8b8e-08f4b697a08c.jpg)

Quelqu'un aurait il une idée d'où cela peut venir et comment le supprimer ? 

Merci !

**Comment by bastyen** [comment]
Bonjour,

c'est un fichier statique disponible dans src/assets/map/zone/zone.geojson

Il sert à afficher la zone du parc si besoin. Il suffit de modifier les coordonnées de la géométrie du fichier donc un tableau vide [] si aucune zone à afficher.

**Comment by JeanLenormand** [comment]
Problème réglé, merci @bastyen
