### ISSUE TITLE
V3 - Error in app/components/map-trek-viz/map-trek-viz.component.ts

### ISSUE THREAD

**Issue by JeanLenormand** [GeotrekCE/Geotrek-mobile#269]
Bonjour,
j'ai les erreurs suivantes en déployant la version 3.3.4 pour Android :

**BROWSER**
$ionic serve renvoie ->

ERROR in app/components/map-trek-viz/map-trek-viz.component.ts:139:28 - error TS2339: Property 'enableRotation' does not exist on type '{ attributionText: string; TreksfitBoundsOptions: { animate: boolean; padding: number; }; TrekfitBoundsOptions: { animate: boolean; padding: number; }; globalMapIconSize: number; informationIconSize: number; ... 10 more ...; touristicContentLayersProperties: { ...; }; }'.
[ng] 139       if (!environment.map.enableRotation) {
[ng]                                ~~~~~~~~~~~~~~
[ng] app/components/map-treks-viz/map-treks-viz.component.ts:161:28 - error TS2339: Property 'enableRotation' does not exist on type '{ attributionText: string; TreksfitBoundsOptions: { animate: boolean; padding: number; }; TrekfitBoundsOptions: { animate: boolean; padding: number; }; globalMapIconSize: number; informationIconSize: number; ... 10 more ...; touristicContentLayersProperties: { ...; }; }'.
[ng] 161       if (!environment.map.enableRotation) {
[ng]                                ~~~~~~~~~~~~~~
[ng]

[INFO] Development server running!
       
       Local: http://localhost:8100
       
       Use Ctrl+C to quit this process

[INFO] Browser window opened to http://localhost:8100!

[ng] ℹ ｢wdm｣: Failed to compile.
[ng] ℹ ｢wdm｣: Compiling...
[ng] ℹ ｢wdm｣: wait until bundle finished: /
[ng] Date: 2020-05-01T09:04:06.665Z - Hash: 564683cb2f550adaa6a1
[ng] 6 unchanged chunks
[ng] Time: 35783ms
[ng] ℹ ｢wdm｣: Compiled successfully.
[ng]    
[ng]     ERROR in src/app/components/map-trek-viz/map-trek-viz.component.ts(139,28): error TS2339: Property 'enableRotation' does not exist on type '{ attributionText: string; TreksfitBoundsOptions: { animate: boolean; padding: number; }; TrekfitBoundsOptions: { animate: boolean; padding: number; }; globalMapIconSize: number; informationIconSize: number; ... 10 more ...; touristicContentLayersProperties: { ...; }; }'.
[ng]     src/app/components/map-treks-viz/map-treks-viz.component.ts(161,28): error TS2339: Property 'enableRotation' does not exist on type '{ attributionText: string; TreksfitBoundsOptions: { animate: boolean; padding: number; }; TrekfitBoundsOptions: { animate: boolean; padding: number; }; globalMapIconSize: number; informationIconSize: number; ... 10 more ...; touristicContentLayersProperties: { ...; }; }'.
[ng]

**BUILD**
$ionic cordova build android --prod --release renvoie->

ERROR in app/components/map-trek-viz/map-trek-viz.component.ts:139:28 - error TS2339: Property 'enableRotation' does not exist on type '{ attributionText: string; TreksfitBoundsOptions: { animate: boolean; padding: number; }; TrekfitBoundsOptions: { animate: boolean; padding: number; }; globalMapIconSize: number; informationIconSize: number; ... 10 more ...; touristicContentLayersProperties: { ...; }; }'.

139       if (!environment.map.enableRotation) {
                               ~~~~~~~~~~~~~~
app/components/map-treks-viz/map-treks-viz.component.ts:161:28 - error TS2339: Property 'enableRotation' does not exist on type '{ attributionText: string; TreksfitBoundsOptions: { animate: boolean; padding: number; }; TrekfitBoundsOptions: { animate: boolean; padding: number; }; globalMapIconSize: number; informationIconSize: number; ... 10 more ...; touristicContentLayersProperties: { ...; }; }'.

161       if (!environment.map.enableRotation) {
                               ~~~~~~~~~~~~~~

[ERROR] An error occurred while running subprocess ng.
       
        ng run app:ionic-cordova-build:production --platform=android exited with exit code 1.
       
        Re-running this command with the --verbose flag may provide more information.

Si quelqu'un a des infos, je suis preneur !
Merci,
Jean

**Comment by camillemonchicourt** [comment]
L'erreur indique que la propriété ``enableRotation`` n'existe pas. 
Dans la version 3.3.4, 2 paramètres ont été ajoutés (https://github.com/GeotrekCE/Geotrek-mobile/commit/965d8d9d6b0dc75a8efeb4e906872727b73d2703#diff-df007a1656e177fcb00b0b9b57323c53) dont ``enableRotation``.

As-tu bien rajouté ces paramètres dans les fichiers ``environment.prod.ts`` et ``environment.ts`` ?
Si tu es récupéré tes fichiers de configuration de la version précédente, tel quel c'est peut-être la source du problème car il manque les valeurs pour les 2 nouveaux paramètres ?

**Comment by JeanLenormand** [comment]
En effet les fichiers de conf. venaient de la version précédente. My fault.. Merci @camillemonchicourt
