### ISSUE TITLE
Error build 3.3.4

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-mobile#270]
Bonjour, 
depuis l'utilisation de la version 3.3.4 lors de la commande ionic cordova build android --prod --release, l'apk est bien créée mais ne s'installe pas sur le smartphone.

Je ne sais pas trop ce qu'il faut fournir pour aider à debugger, voici par défaut : 

 - les logs de la compilation avec la commande ionic cordova build android --prod --release --verbose : [build_android.log](https://github.com/GeotrekCE/Geotrek-mobile/files/4608996/build_android.log)
 - le fichier config.xml : [config.xml.txt](https://github.com/GeotrekCE/Geotrek-mobile/files/4609024/config.xml.txt)

 - le fichier environment.prod.ts : [environment.prod.ts.txt](https://github.com/GeotrekCE/Geotrek-mobile/files/4609012/environment.prod.ts.txt)

J'ai remarqué pendant la compilation de l'apk ces messages : 

> WARNING in /Users/Michael/Geotrek-mobile/src/zone-flags.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

>WARNING in /Users/Michael/Geotrek-mobile/src/environments/environment.prod.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

J'ai essayé de chercher un peu mais ça sort de mon domaine de compétence. 

Infos supplémentaires - j'ai fait ces manipulations de customisation supplémentaires : 

- modifié dans environment.prod.ts : le center de la map online et offline
- variables.ts : la couleur pour que ce soit la même que dans theme/variables.scss
- ajouté le dossier analytics avec les fichiers analytics pour android et ios
- ajouté les lignes correpondantes à firebase dans le config.xml
- modifié le splashscreen et l'icon puis utilisé la commande ionic cordova resources
- utilisé un workaround pour les images dans le config.xml pour ne plus avoir de messages d'erreurs concernant le missing default files (voir : https://github.com/apache/cordova-android/issues/689#issuecomment-473992821 )

Je précise que ces manipulations ont déjà été faites sur une version plus ancienne et l'application s'installait sans soucis. J'avais juste fait la manipulation pour enlever firebase. C'est depuis que je veux le mettre en place que j'ai le problème.

S'il il y a d'autres informations à fournir et/ou de fichiers, je ferai le nécessaire.

**Comment by mviadere-openig** [comment]
Bonjour, 

J'ai fait des tests hier, l'application fonctionne lorsqu'on la run sur avec un emulator.

Lorsque je récupère directement le app-debu.apk et que je l'installe sur le smartphone, cela fonctionne aussi. C'est uniquement lorsque je veux build la version release que cela ne veut pas s'installer.

**Comment by camillemonchicourt** [comment]
Je pense que tes soucis viennent de tes manipulations avec Firebase et non pas à la release 3.3.4.

**Comment by mviadere-openig** [comment]
Je suis en train de regarder, effectivement le problème de vient pas de la release, il y a pleins de raisons qui font qu'une application ne s'installe pas sur un smartphone. Je vais essayer sur mon smartphone personnel pour tester, mais si ça fonctionne sans problème sur l'émulateur c'est que le problème n'est pas lié à la release.

**Comment by mviadere-openig** [comment]
Concernant mon problème,j'ai récupéré à nouveau les fichiers firebase et j'ai signé l'application (voir ici : https://ionicframework.com/docs/deployment/play-store). Mon problème pouvait venir d'une de ces manipulations. Il est résolu.
