### ISSUE TITLE
V3 / IOS, accès aux données distantes bloqués

### ISSUE THREAD

**Issue by JeanLenormand** [GeotrekCE/Geotrek-mobile#272]
Bonjour,

le 18 juin 2020 j'ai déposé l'application Via Columbani sur les stores Apple et Google.

L'application fonctionne sans problème sur Android.
Par contre, j'ai un problème avec l'application IOS. L'application a parfaitement fonctionné durant les périodes de tests et après sa mise en ligne, mais depuis mercredi dernier 24/06, l’accès aux données distantes semble bloqué.

GTM V3.3.4.
Données accessibles sur un VPS en Ubuntu 18.04 de chez OVH qui héberge aussi GTR en 2.24.0.

Cf capture d'un Iphone8 ci dessous :

![IMG-20200702-WA0000](https://user-images.githubusercontent.com/33653562/86377576-cb439700-bc88-11ea-9726-fbd83d13af86.jpg)

Je n'arrive pas à avoir de réponse concrète de la part du "service technique" d'Apple. Si quelqu'un a des pistes, je suis preneur !

Merci,

Jean

**Comment by bastyen** [comment]
Aucune idée
C'est étrange si du jour au lendemain l'application n'accède plus aux données et seulement sur iOS

**Comment by JeanLenormand** [comment]
@bastyen, merci pour ton retour. Le problème a été résolu après génération d'une nouvelle version de l'application.
N'étant pas expert de Xcode je me trompe peut-être, mais j'ai l'impression qu'une fois le projet Xcode généré, si un changement est effectué dans les fichiers .ts du dossier /src, ces changements ne sont pas pris en compte par Xcode. Problème qui ne se pose pas pour l'application Androïd puisque aucun logiciel n'est imposé pour générer les .apk.
