### ISSUE TITLE
Geotrek 3.3.4 question concernant UIBackgroundModes dans info.plist

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-mobile#274]
Version : 3.3.4

Bonjour,on a pu depuis juin déployer une version de l'application pour android sans problèmes. On est passé depuis à la version pour ios. On a soumis plusieurs binaires à l'applestore qui à chaque fois on été refusé. Apple communique très bien mais est plutôt tatillons sur certains détails. Bref voilà où on en est actuellement pour résumer.

Concernant ma question, voici un extrait de leur derniers messages : 

> Your app declares support for location in the UIBackgroundModes key in your Info.plist file but does not have any features that require persistent location. Apps that declare support for location in the UIBackgroundModes key in your Info.plist file must have features that require persistent location.
> 
> Next Steps
> 
> To resolve this issue, please revise your app to include features that require the persistent use of real-time location updates while the app is in the background.
> 
> If your app does not require persistent real-time location updates, please remove the "location" setting from the UIBackgroundModes key. You may wish to use the significant-change location service or the region monitoring location service if persistent real-time location updates are not required for your app features.

Alors j'ai trouvé la key sans problèmes et je peux le modifier, mais avant de le faire j'aimerais savoir l'avis de @bastyen pour savoir s'il faut vraiment le faire, si l'application à vraiment besoin de la localisation de façon permanente, où bien si je dis à apple que je préviendrais les utilisateurs de l'application dans la description cela devrait leur suffire ? Je n'ai honnêtement jamais utilisé l'application de façon pratique et je n'ai pas de retours utilisateurs spécifiques.

Merci à l'avance pour vos réponses et bonne journée à vous !

**Comment by bastyen** [comment]
Salut,

il faut que tu explique à Apple où et pourquoi on a besoin de la géolocalisation en background.

> We are using UIBackgroundModes to notify user when he's near of an point of interest.
> To do so, user need to push 'Activer les notifications' button on map (Click on one item of trek list then click on fab button map, here's the button).
> We never start background geolocalisation without an action from the user.

Il est possible que le support te demande une video de cette manipulation par la suite.

Si tu enlève la clé UIBackgroundModes, la géolocalisation ne fonctionnera plus

**Comment by mviadere-openig** [comment]
Merci pour ce retour @bastyen.
