### ISSUE TITLE
Questions concernant le déploiement pour iOS / fonctionnement de l'api avec émulateur

### ISSUE THREAD

**Issue by mviadere-openig** [GeotrekCE/Geotrek-mobile#275]
Bonjour,

Est-il possible de faire fonctionner l'api lorsque l'on run l'application sous émulateur ? 

J'ai besoin de la réponse car j'ai demandé un rdv avec un représentant d'apple pour l'application que l'on souhaite déployer, car depuis fin juin, parmi la dizaine de binaires refusés, une des raisons remis en avant à chaque fois est qu'il n'arrive pas à afficher du contenu dans l'application, où bien que les filtres ne fonctionne pas, etc. J'ai mis en PJ un résumé des refus de binaire. 

De notre côté à chaque fois on a envoyé une vidéo à l'appui pour montrer que l'application fonctionne sans problèmes, on leur a bien précisé qu'il faut essayer sur un appareil physiques, on a même  configuré l'iphone en région et langue US, mais on arrive pas à reproduire leur problème. 

Je sais que ce n'est pas vraiment un problème de l'application en elle-même, elle fonctionne très bien, mais j'aimerais avoir si possibles des retours sur ce genre d'expériences, si vous en avez déjà rencontrées, etc.

Merci encore à vous.
[liste_refus_binaire.docx](https://github.com/GeotrekCE/Geotrek-mobile/files/4971903/liste_refus_binaire.docx)

**Comment by bastyen** [comment]
Salut,

as-tu vérifié la présence de contenu pour la langue courante de l'utilisateur ?

Si par exemple, tu as laissé la langue 'en' de disponible dans la variable d'environnement des langues disponibles alors il faut s'assurer qu'au moins une randonnée est disponible pour cette langue. 
Sinon l'api renvoi aucun element et donc l'application est vide, et Apple ne pourra faire fonctionner l'application correctement.

**Comment by mviadere-openig** [comment]
Merci, effectivement j'avais laissé la langue 'en' dans la variable d'environnement. Je vais la retirer et soumettre un nouveau binaire.

**Comment by mviadere-openig** [comment]
Bonjour, voici ce que j'ai mis dans environment.prod.ts : 
`availableLanguage: ['fr'],`

J'ai ensuite rebuild l'app, et j'ai soumis cette version, j'ai encore un problème :

> We discovered one or more bugs in your app when reviewed on iPad running iOS 13.6 on Wi-Fi.

>Specifically, the app is not finding and /or displaying any treks or maps when we try to find them with filtering or searching.


Est-ce qu'il y a un réglage spécifique à faire concernant les iPad ?

**Comment by bastyen** [comment]
Non, l'application pour iPad se comporte de la même manière que l'application pour iPhone.

Quand tu dis avoir rebuild l'app, c'est seulement depuis `xCode` ou aussi avec `ionic cordova build ios` ?

**Comment by mviadere-openig** [comment]
uniquement depuis Xcode, j'ai choisi generic device en haut à gauche. Dans General > Identity j'ai changé le numero de version et de build, puis j'ai fait dans le Menu du haut Product > Archive.

**Comment by bastyen** [comment]
Dans ce cas, je ne pense pas que la modification soit prise en compte. 
Avant de créer ton build depuis `xCode`, exécute la commande `ionic cordova build iOS`

**Comment by mviadere-openig** [comment]
Bonjour @bastyen,

Merci pour cette remarque, c'est effectivement ce qu'il manquait pour pour la soumission du binaire. Je note ici pour les prochaines personnes qui aurait le problème : 

 - il faut d'abord faire le build en CLI (via la commande `ionic cordova build ios --prod --release`)
 - faire la manipulation sur Xcode pour créer l'archive,
 - penser à changer le build sur la page de l'application de l'AppStore Connect et soumettre.

Le problème est résolu, je clos l'issue.
