### ISSUE TITLE
Changer le lien vers les "Règles de confidentialité" sur la fiche Google Play afin de pouvoir publier une nouvelle release

### ISSUE THREAD

**Issue by blaisegeo** [GeotrekCE/Geotrek-mobile#285]
Bonjour;
Nouvellement arrivé au Parc National de la Vanoise, je suis en charge des sites et applis Geotrek.
L'appli mobile android actuellement disponible ( juillet 2021) sur Google Play (Rando Vanoise, version 2.4.0 publiée le 8 juin 2016) plante dès le démarrage avec une image floue figée.
Je suis arrivé à compiler un nouvel apk qui fonctionne maintenant correctement en l'installant manuellement sur un téléphone.
Après l'avoir signé et zipé je cherche maintenant à le publier sur Google Play, mais avec deux tentatives infructueuses depuis une semaine.

Le retour de Google a été deux fois le même:
Eligibility Issue:
Privacy policy
You must provide a link to your app's privacy policy on your app's store listing page. This link must be maintained at all times while the app is available on Google Play, and it must link to a privacy policy that, among other things, accurately describes your app’s data collection and use. Please provide a link to a valid privacy policy in your app's store listing page in the Play Console. For more details, please refer to the Privacy policy section (#6) of the Families Policy Requirements.

En effet, sur la page Google Plauy de l'appli ( https://play.google.com/store/apps/details?id=com.makinacorpus.pnvanoise ), le lien des "Règles de confidentialité" tout en bas à gauche de la fiche est un lien mort qui point sur:
https://www.vanoise-parcnational.fr/fr/mentions-legales.html
Le bon lien, valide,  est exactement le même, mais sans le point ni l'extension html à la fin:
https://www.vanoise-parcnational.fr/fr/mentions-legales

Je suis donc allé dans la Google Play Console, dans les pages d'administration de l'application en question, et tout en bas de la colonne de gauche, sur le lien 'Contenu de l'application". Sur cette page, je clique sur le lien "Gérer" du paragraphe "Règles de confidentialité" et là se trouve la ligne à éditer pour changer ce lien. J'ai enlevé le ".html" à la fin du lien, puis validé avec le bouton bleu "Enregistrer" en bas à droite de la page.

Cependant, lorsque je rafraîchis la fiche de l'application sur Google Play, le lien est toujours l'ancien, le mauvais, avec ".html" à la fin.
J'ai pensé qu'il fallait attendre un certain temps pour que ce changement soit pris en compte, mais après 2 jours, toujours pas de changement.

J'ai alors pensé qu'il fallait que je republie la nouvelle release, pour que ce changement de lien soit pris en compte, mais non, au bout de 3 jours, Google m'a répondu toujours la même chose: qu'il fallait un lien valide pour ces Règles de confidentialité.
J'ai alors contesté le refus de publication en expliquant bien que j'avais modifié ce lien problématique, et enregistré le changement, que je voyais bien le changement effectif sur la Console en étant authentifié comme administrateur, mais pas sur la fiche en la consultant en tant que simple visiteur.

J'ai obtenu une réponse cette fois-ci un peu plus vite m'indiquant qu'il y avait bien un problème, toujours le même, avec ma "Privacy policy":
Step 1: Fix the policy violation with your app
During review, we found that your app does not link to a valid privacy policy on your app’s store listing page. This link must be maintained at all times while the app is available on Google Play, and it must link to a privacy policy that, among other things, accurately describes your app's data collection and use.

Je ne sais plus que faire pour arriver à publier la nouvelle release.
Le changement du lien vers les Règles de confidentialité que j'ai effectué est-il bien pris en compte, et si non comment faire pour que ce soit le cas ?
S'il est pris en compte (ce que je doute) alors que manque-t-il dans la page des Mentions légales pour que Google l'accepte comme valide ? Il ne faut quand même pas la traduire en anglais et mettre en toutes lettres "Privacy Policy" comme c'est indiqué dans la réponse à ma contestation du refus de publication ?

Je suis à court d'idées et j'en viens à imaginer de générer la même appli mais avec un nom différent pour enfin pouvoir mettre le bon lien vers les Règles de confidentialité à la création.
J'ai bien conscience que ce problème n'est pas directement lié à l'appli Geotrek-mobile mais peut-être quelqu'un saura me conseiller dans ce processus de publication ?
D'avance merci.
Blaise

**Comment by camillemonchicourt** [comment]
Ça fait un bon moment que l'on n'utilise plus la version 2 de Geotrek-mobile donc je pense que ça va être compliqué voire impossible de la publier sur Google play vu toutes les évolutions de contraintes d'Android depuis...
Je conseille clairement de passer en v3 car la v2 n'est plus maintenue.

**Comment by blaisegeo** [comment]
Bien compris, merci. Un des objectifs de ma mission est bien de migrer en v3, mais en attendant, ayant résolu le problème qu'il y avait sur l'appli v2, j'aurais souhaité la publier, mais je n'arrive pas à faire comprendre à la console Android que j'ai actualisé le lien vers les Mentions légales. Dommage.

**Comment by camillemonchicourt** [comment]
Oui là je ne sais pas, c'est un sujet lié à Google Play de ce que je comprends, indépendant de Geotrek-mobile si je comprends bien.

**Comment by ffournier** [comment]
Bonjour,

je suis toujours abonné a ce projet .

Mais sinon voici les règles de RGPD de Google PLay qui a changé depuis le
début de cette année suite au évolution des lois européennes sur le sujet.

https://support.google.com/googleplay/android-developer/answer/9859455?hl=fr
.

Si je ne dis pas de connerie de mémoire l'application collecte des données
de géolocalisation.
Donc de ce fait elle doit etre conforme. Ajout de la RGPD EU dans l'app +
renseignement depuis le google play.

Bonne journée.

**Comment by bastyen** [comment]
le problème est bien celui qu'évoque @ffournier\
j'ai rendu conforme la V3 cette année, elle affiche un message à l'utilisateur pour lui expliquer pourquoi l'application demande le droit de géolocalisation dfa434b\
https://support.google.com/googleplay/android-developer/answer/9799150
