### ISSUE TITLE
Statistiques Geotrek rando Geotrek mobile

### ISSUE THREAD

**Issue by AudreyRemy** [GeotrekCE/Geotrek-mobile#286]
Bonjour,
N’ayant pu assister aux rencontres, j’ai visionné la présentation faite sur l’application mobile mais je suis à la recherche de renseignements complémentaires.
Pour les utilisateurs de Geotrek mobile et Geotrek rando, pourriez-vous me communiquer :
•	Le nombre de visiteurs de la page home Geotrek rando
•	Le nombre de consultations de fiche itinéraire
•	Le taux de chargement de Geotrek mobile
•	Le taux de déchargement de Geotrek mobile
•	L’investissement en communication pour faire connaître l’application mobile
Merci d’avance pour vos retours.
Bonne journée.

**Comment by camillemonchicourt** [comment]
Salut, c'est très (très) variable d'un Geotrek à un autre, selon la dynamique territoriale et de communication.
Aux rencontres 2016, on avait fait une petite synthèse de statistiques de différents Geotrek-rando et Geotrek-mobile, disponible ici : https://geotrek.ecrins-parcnational.fr/rencontres/2016/01-etat-lieux-usages-Geotrek.pdf

Il y a aussi eu différents échanges sur le sujet sur la liste de diffusion : 
- https://groups.google.com/g/geotrek-fr/c/mHnZdWOjlQA/m/KrnDD6R5CwAJ
- https://groups.google.com/g/geotrek-fr/c/xNJUePVLWbI/m/BBpNpZHBAwAJ
- https://groups.google.com/g/geotrek-fr/c/XxyZqAft9pQ/m/tz8t7l-xEgAJ
- https://groups.google.com/g/geotrek-fr/c/rsYSMYwZC_o/m/1EMXFIH9f9UJ

Aux rencontres Geotrek 2019, il y avait eu un atelier sur le référencement et la communication autour d'un portail Geotrek : 
- https://geotrek.ecrins-parcnational.fr/rencontres/2019/ateliers/A4-SEO-COM-PNE.pdf
- https://geotrek.ecrins-parcnational.fr/rencontres/2019/ateliers/A4-SEO-COM-PDE.pdf

Aux rencontres 2021, il y a eu un atelier de réflexion sur la complémentarité entre les outils Geotrek-rando et Geotrek-mobile, avec une synthèse des discussions à la fin de la présentation : https://geotrek.ecrins-parcnational.fr/rencontres/2021/ateliers/geotrek-atelier-mobile.pdf

Bonne journée.
