### ISSUE TITLE
Prob GPS V3/Android12

### ISSUE THREAD

**Issue by thomaspnrhj** [GeotrekCE/Geotrek-mobile#287]
Bonjour,
Nous avons eu cet avis sur G.Play et plusieurs soucis GPS du même ordre de remonter à des OT 
"J´avais utilisé cette appli avec bonheur en 01/2021 . De retour dans le Jura en 03/2022, grosse déception : le point gps ne s´actualise plus pendant la rando à moins de fermer l'appli puis de la ré ouvrir. Le point GPS s´actualise alors puis se fige de nouveau. Bref, inutilisable pendant la rando. J´espère que ce bug va vite être résolu car avant ce problème j´étais fan des applis randos de cet éditeur ! 2 * quand même pour la recherche et les infos sur les randos disponibles alentour."

Vous avez dejà eu des remontées similaires ? La personne était sous Samsung Galaxy S10 et en Android 12
Pour mémoire on est en V3 depuis juin 2020

**Comment by camillemonchicourt** [comment]
Quelle version de l'application, car il y a eu plusieurs versions sorties depuis juin 2020 : https://github.com/GeotrekCE/Geotrek-mobile/releases.

Il y a certainement eu des évolutions réalisées liées aux nouvelles versions d'Android.

**Comment by thomaspnrhj** [comment]
Ok j'avais pas vu les sous-versions.... On est à priori en 3.3.4, il y a l'air d'avoir pas mal de correctif dans les versions suivantes,  je vais voir avec Makina pour une montée de version. 
Merci chef !
Thomas
