### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-mobile#289]
Je ne vois plus d'indications dans la documentation pour mettre en place un outil de suivi des statistiques d'utilisation de l'application. Est-ce toujours possible dans la version actuelle?

**Comment by bastyen** [comment]
L'application ne supporte plus, de base, un analytics. Néanmoins, vous pouvez facilement ajouter celui de votre choix.
De notre côté, nous ajoutons Matomo lorsqu'on nous le demande car, la plupart du temps, les statistiques des stores sont suffisantes. C'est très simple et rapide à mettre en place avec `npx ng add @ngx-matomo/tracker`.

**Comment by bastyen** [comment]
C'est possible avec Matomo. De base, vous aurez des statistiques plus précises mais pour certaines comme le nombre de téléchargements, vous devez ajouter vous même la ligne de code nécessaire.
