### ISSUE TITLE
Titre des itinéraires non traduits dans la liste

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-mobile#291]
Lorsqu'on est sur une autre langue que le FR, les titres des itinéraires n'apparaissent pas dans leur version traduite dans la liste des randos mais sont bien traduits lorsqu'on est sur la fiche itinéraire

![IMG_8783](https://user-images.githubusercontent.com/44799642/191222816-3408282a-8deb-4b22-80b0-7bcda4ce1418.PNG)
![IMG_8782](https://user-images.githubusercontent.com/44799642/191222844-3d543595-4e52-4238-b6dc-0ac69c442526.PNG)

**Comment by bastyen** [comment]
C'est un problème de cache.

Dans un premier temps, vous pouvez vider le cache de l'application puis la lancer afin d'avoir les données avec la bonne traduction.
Dans un second temps, il faut ajouter `add_header Vary "Accept-Language";` dans la conf nginx qui concerne le mobile afin que l'application puisse savoir qu'il ne faut pas utiliser une réponse en cache si la langue n'est pas la même.

De plus, je vous préviens que la prochaine version de Geotrek mobile utilisera un client http natif et ne demandera plus une configuration spécifique concernant `Accept-Language` côté serveur ainsi que pour les cors.

**Comment by pnrma** [comment]
Effectivement, après vidage du cache cela fonctionne bien, merci.
J'ai tenté d'ajouter `add_header Vary "Accept-Language";`  dans la partie `location ~ ^/mobile/(.*)$ ` de la conf nginx du Geotrek-rando mais dans mon cas cela ne semble pas fonctionner car après changement de langue du mobile, on a toujours les titres dans la langue précédente.
Ok je note pour le client natif pour la prochainea version.

**Comment by bastyen** [comment]
Vous avez à nouveau supprimer le cache après le changement de la conf ?
C'est nécessaire car sinon l'application a encore en cache l'ancienne réponse qui ne contenait pas ce header.

**Comment by pnrma** [comment]
Au temps pour moi, ça fonctionne après avoir désinstallé et réinstallé l'application.
Problème résolu donc, merci !
