### ISSUE TITLE
Echelle de zoom et attribution sur carte randonnée

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-mobile#293]
Version 3.10.0, l'échelle de la carte et l'attribution sur les fiches randonnées n'apparaissent pas. Cela apparait bien sur la carte générale.
Est-ce un problème de paramétrage ou s'agit-il d'un bug?

![image](https://user-images.githubusercontent.com/44799642/193825005-68c3348a-46b4-403c-8b2d-d3aa54a1d18e.png)

![image](https://user-images.githubusercontent.com/44799642/193824825-a9fa198e-cc45-49f8-8635-e79ddd8313d9.png)

**Comment by pnrma** [comment]
Exact ! Je m'étais focalisé sur l'échelle qui pour le coup est complètement masquée...
Histoire de gagner du temps, est-ce que tu peux me dire comment déplacer ce bouton si tu le sais?

**Comment by camillemonchicourt** [comment]
Ah la technique ça me dépasse.
Mais je dirai qu'il faut style ce bloc pour lui ajouter une marge bottom plus haute ou un truc du genre - https://github.com/GeotrekCE/Geotrek-mobile/blob/main/src/app/components/geolocate-notifications/geolocate-notifications.component.html#L6

**Comment by bastyen** [comment]
J'avais vu ce détail. J'ai oublié de le rectifier. Je m'en occupe.

**Comment by pnrma** [comment]
Top, merci.

**Comment by bastyen** [comment]
65cd963b8b77ee1f46119c122cf8a82de9ceb368
Merci pour le retour.
