### ISSUE TITLE
Temps d'affichage Splashscreen

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-mobile#296]
Y a t-il un moyen de définir la durée d'affichage du Splashscreen à l'ouverture de l'appli ?

**Comment by bastyen** [comment]
Oui et non.
C'est faisable mais actuellement, celle-ci attend de récupérer les données avant de cacher le splashscreen.
Donc pour pouvoir le faire, il faudrait remplacer ce fonctionnement.
