### ISSUE TITLE
Ajout d'un accueil, d'un menu, d'une page secours et d'une fonction permettant de se rendre à une rando ou un lieu d'information

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-mobile#297]
Dans le cadre d'évolutions financés par le projet Alès Agglo Evasion, différentes évolutions ont été intégrées dans la version 3.10.6 : 

- Ajout d'un menu à la place des onglets de navigation en bas de l'application : 

![Screenshot_20230215_140232_io ales geotrek](https://user-images.githubusercontent.com/4418840/219864742-6efa1dea-c6b2-4898-80f2-d88813ef1335.jpg)

Si ce menu n'est pas configuré, ce sont les onglets en bas de page qui continuent à permettre de naviguer dans les différentes pages : 

![Screenshot_20230218_130218_com makinacorpus randoecrins](https://user-images.githubusercontent.com/4418840/219864849-83e5aa80-ff44-487f-99cd-4a5a37818bba.jpg)

- Si le menu est configuré, une page d'accueil est proposée quand on accède à l'application : 

![Screenshot_20230215_140032_io ales geotrek](https://user-images.githubusercontent.com/4418840/219864925-5efe8f36-c6e8-4e25-8395-d2950320ab3b.jpg)

- Si le menu est configuré, une page d'appel des secours et de localisation est accessible : 

![Screenshot_20230215_140049_io ales geotrek](https://user-images.githubusercontent.com/4418840/219864979-73ae2747-9ce8-4475-92e7-745aaff1241d.jpg)

Le numéro de téléphone utilisé st configurable : https://github.com/GeotrekCE/Geotrek-mobile/commit/5d3deed1026542069a33760dcbea22da0aed38e3#diff-cf1c320ecea58ee575e020a2dc907817b09fe6bce687077303cd35bbda7ed405R10

- Une fonctionnalité permettant de se rendre au point de départ d'un rando ou à un lieu de renseignement.
  Quand on clique sur "Y aller", cela ouvre une application de navigation présente sur l'appareil mobile en proposant un itinéraire vers ce point.

![Screenshot_20230215_140340_io ales geotrek](https://user-images.githubusercontent.com/4418840/219865171-e42c390a-cc37-4c5f-b5f9-ff9125c7b0eb.jpg)

![Screenshot_20230215_150419_io ales geotrek](https://user-images.githubusercontent.com/4418840/219865178-b43ca2c3-e07a-42d1-9e2a-650d4cbec999.jpg)

**Comment by camillemonchicourt** [comment]
Précisions de @bastyen :

- Actuellement, pour activer le menu, il faut renseigner ``menu`` au lieu de ``tabs`` pour la variable ``navigation`` dans le fichier d'environnement (https://github.com/GeotrekCE/Geotrek-mobile/blob/3.10.6/src/environments/environment.prod.ts#L12)
- Une fois en mode ``menu``, la page accueil affiche automatiquement les pratiques, le secours et bientôt un lien vers l'application Suricate
- Le mode ``tabs`` restera celui par défaut
- La fonction "Y aller" est disponible d'office, elle est désactivé par défaut pour les POI, activable dans le fichier d'environnement car par exemple y aller pour un POI de type faune et flore n'est pas très utile (https://github.com/GeotrekCE/Geotrek-mobile/blob/3.10.6/src/environments/environment.prod.ts#L13)
- On pourrait facilement rendre activable ou pas le secours, le lien vers l'application Suricate et même la fonctionnalité "Y aller" si on veut

**Comment by bastyen** [comment]
Il en résulte qu'on doit fournir plus d'informations dans le readme.
