### ISSUE TITLE
Intégration des sites et parcours outdoor

### ISSUE THREAD

**Issue by pnrma** [GeotrekCE/Geotrek-mobile#298]
Une intégration des sites et parcours outdoor est-elle prévue dans les prochaines versions de l'application?

**Comment by camillemonchicourt** [comment]
Non, pas à ma connaissance.

**Comment by pnrma** [comment]
ok merci pour la réponse.

**Comment by bastyen** [comment]
Nous continuons de maintenir l'application pour qu'elle utilise les derniers versions des technologies utilisées et on facilite sa création.
On a récemment amélioré l'UI et ajouté un nouveau système de navigation mais c'était financé.
Nous aimerions ajouté l'outdoor mais comme l'a dit @camillemonchicourt  ce n'est pas prévu pour le moment.
